PROGRAM datagen

! The purpose of this program is to take a lammps data file generated by MAPS
! and alter it to put the OPLS-AA force field for PMMA
! Right now it's only for PMMA, but it could be changed to be versitile

IMPLICIT NONE

INTEGER        :: i,j
INTEGER        :: natomtypold
INTEGER        :: iatom, imolecule, iatypeold
INTEGER        :: atom1, atom2, atom3, atom4, dummyint
INTEGER        :: atomtype1, atomtype2, atomtype3, atomtype4
INTEGER        :: natoms, nbonds, nangles, ndihedrals, nimpropers
INTEGER        :: natomtyp, nbondtyp, nangletyp, ndihedraltyp, nimpropertyp
INTEGER        :: newbondtyp, newangletyp, newdihedraltyp
INTEGER,ALLOCATABLE,DIMENSION(:) :: iatypenew
REAL           :: xlo, xhi, ylo, yhi, zlo, zhi
REAL           :: tempcharge, x, y, z
REAL,PARAMETER :: tol = .0001
REAL,ALLOCATABLE,DIMENSION(:) :: icharge, imass, sigma, eps
REAL,ALLOCATABLE,DIMENSION(:) :: kbond, rbond
REAL,ALLOCATABLE,DIMENSION(:) :: kangle, theta
REAL,ALLOCATABLE,DIMENSION(:) :: V1, V2, V3, V4
REAL,ALLOCATABLE,DIMENSION(:) :: kangleimp, thetaimp

CHARACTER(120) :: dummy,datafile,datafilenew, dummy1
CHARACTER(4),ALLOCATABLE,DIMENSION(:)  :: atypenew
CHARACTER(4),ALLOCATABLE,DIMENSION(:)  :: btype1, btype2
CHARACTER(4),ALLOCATABLE,DIMENSION(:)  :: agltype1, agltype2, agltype3
CHARACTER(4),ALLOCATABLE,DIMENSION(:)  :: dtype1, dtype2, dtype3, dtype4
CHARACTER(4),ALLOCATABLE,DIMENSION(:)  :: itype1, itype2, itype3, itype4

INTEGER,ALLOCATABLE,DIMENSION(:)  :: intatypenew
INTEGER,ALLOCATABLE,DIMENSION(:)  :: intbtype1, intbtype2
INTEGER,ALLOCATABLE,DIMENSION(:)  :: intagltype1, intagltype2, intagltype3
INTEGER,ALLOCATABLE,DIMENSION(:)  :: intdtype1, intdtype2, intdtype3, intdtype4
INTEGER,ALLOCATABLE,DIMENSION(:)  :: intitype1, intitype2, intitype3, intitype4

LOGICAL                           :: first
LOGICAL                           :: found

OPEN(UNIT=11,FILE='datagen.ctrl',STATUS='OLD',ACTION='READ')

! read the control file
READ(11,*)            ! Read comment line and throw away
READ(11,*) datafile, datafilenew   !  lammps datafile
datafile = TRIM(datafile)
datafilenew = TRIM(datafilenew)
READ(11,*)            ! Read comment line and throw away
READ(11,*) natomtyp   ! Number of atom types in your sim -> this is what natomyp is for
ALLOCATE(icharge(natomtyp))        ! Allocate all the sizes based on the number of atom type
ALLOCATE(imass(natomtyp))
ALLOCATE(atypenew(natomtyp))
ALLOCATE(sigma(natomtyp))
ALLOCATE(eps(natomtyp))
ALLOCATE(intatypenew(natomtyp))
READ(11,*)				! Throw away header of table

DO i = 1, natomtyp  	! Read all data from table for the number of atoms
   READ(11,*) atypenew(i), sigma(i), eps(i), icharge(i), imass(i)
   intatypenew(i) = i 
END DO

READ(11,*) 
READ(11,*) nbondtyp   ! Number of bond types in your sim
ALLOCATE(kbond(nbondtyp),rbond(nbondtyp))
ALLOCATE(btype1(nbondtyp),btype2(nbondtyp))
ALLOCATE(intbtype1(nbondtyp),intbtype2(nbondtyp))
intbtype1(:) = 0
intbtype2(:) = 0
READ(11,*) 

DO i = 1, nbondtyp
   READ(11,*) btype1(i), btype2(i), kbond(i), rbond(i)
   DO j = 1, natomtyp
      IF(btype1(i) == atypenew(j)) intbtype1(i) = j
      IF(btype2(i) == atypenew(j)) intbtype2(i) = j
   END DO
   IF(intbtype1(i) == 0) THEN
      WRITE(*,*) 'Could not find type 1 for bond', i
      STOP
   ELSE IF(intbtype2(i) == 0) THEN
      WRITE(*,*) 'Could not find type 2 for bond', i
      STOP
   END IF
END DO

READ(11,*) 
READ(11,*) nangletyp   ! Number of angle types in your sim
ALLOCATE(kangle(nangletyp),theta(nangletyp))
ALLOCATE(agltype1(nangletyp),agltype2(nangletyp),agltype3(nangletyp))
ALLOCATE(intagltype1(nangletyp),intagltype2(nangletyp),intagltype3(nangletyp))
intagltype1(:) = 0
intagltype2(:) = 0
intagltype3(:) = 0
READ(11,*)

DO i = 1, nangletyp
   READ(11,*) agltype1(i), agltype2(i), agltype3(i), kangle(i), theta(i)
   DO j = 1, natomtyp
      IF(agltype1(i) == atypenew(j)) intagltype1(i) = j
      IF(agltype2(i) == atypenew(j)) intagltype2(i) = j
      IF(agltype3(i) == atypenew(j)) intagltype3(i) = j
   END DO
   IF(intagltype1(i) == 0) THEN
      WRITE(*,*) 'Could not find type 1 for angle', i
      STOP
   ELSEIF(intagltype2(i) == 0) THEN
      WRITE(*,*) 'Could not find type 2 for angle', i
      STOP
   ELSEIF(intagltype3(i) == 0) THEN
      WRITE(*,*) 'Could not find type 3 for angle', i
      STOP
   END IF
END DO

READ(11,*) 
READ(11,*) ndihedraltyp   ! Number of dihedral types in your sim
ALLOCATE(V1(ndihedraltyp),V2(ndihedraltyp),V3(ndihedraltyp),V4(ndihedraltyp))
ALLOCATE(dtype1(ndihedraltyp),dtype2(ndihedraltyp),dtype3(ndihedraltyp),dtype4(ndihedraltyp))
ALLOCATE(intdtype1(ndihedraltyp),intdtype2(ndihedraltyp),intdtype3(ndihedraltyp))
ALLOCATE(intdtype4(ndihedraltyp))
intdtype1(:) = 0
intdtype2(:) = 0
intdtype3(:) = 0
intdtype4(:) = 0
READ(11,*)

DO i = 1, ndihedraltyp
   READ(11,*) dtype1(i), dtype2(i), dtype3(i), dtype4(i), V1(i), V2(i), V3(i), V4(i)
   DO j = 1, natomtyp
      IF(dtype1(i) == atypenew(j)) intdtype1(i) = j
      IF(dtype2(i) == atypenew(j)) intdtype2(i) = j
      IF(dtype3(i) == atypenew(j)) intdtype3(i) = j
      IF(dtype4(i) == atypenew(j)) intdtype4(i) = j
   END DO
   IF(intdtype1(i) == 0) THEN
      WRITE(*,*) 'Could not find type 1 for dihedral', i
      STOP
   ELSEIF(intdtype2(i) == 0) THEN
      WRITE(*,*) 'Could not find type 2 for dihedral', i
      STOP
   ELSEIF(intdtype3(i) == 0) THEN
      WRITE(*,*) 'Could not find type 3 for dihedral', i
      STOP
   ELSEIF(intdtype4(i) == 0) THEN
      WRITE(*,*) 'Could not find type 4 for dihedral', i
      STOP
   END IF
END DO

READ(11,*) 
READ(11,*) nimpropertyp   ! Number of improper types in your sim
IF(nimpropertyp .GT. 0) THEN
   ALLOCATE(kangleimp(nimpropertyp),thetaimp(nimpropertyp))
   ALLOCATE(itype1(nimpropertyp),itype2(nimpropertyp),itype3(nimpropertyp))
   ALLOCATE(itype4(nimpropertyp))
   ALLOCATE(intitype1(nimpropertyp),intitype2(nimpropertyp),intitype3(nimpropertyp))
   ALLOCATE(intitype4(nimpropertyp))
   intitype1(:) = 0
   intitype2(:) = 0
   intitype3(:) = 0
   intitype4(:) = 0
   READ(11,*)
   DO i = 1, nimpropertyp
      READ(11,*) itype1(i), itype2(i), itype3(i), itype4(i), kangleimp(i), thetaimp(i)
      DO j = 1, natomtyp
         IF(itype1(i) == atypenew(j)) intitype1(i) = j
         IF(itype2(i) == atypenew(j)) intitype2(i) = j
         IF(itype3(i) == atypenew(j)) intitype3(i) = j
         IF(itype4(i) == atypenew(j)) intitype4(i) = j
      END DO
      IF(intitype1(i) == 0) THEN
         WRITE(*,*) 'Could not find type 1 for improper', i
         STOP
      ELSEIF(intitype2(i) == 0) THEN
         WRITE(*,*) 'Could not find type 2 for improper', i
         STOP
      ELSEIF(intitype3(i) == 0) THEN
         WRITE(*,*) 'Could not find type 3 for improper', i
         STOP
      ELSEIF(intitype4(i) == 0) THEN
         WRITE(*,*) 'Could not find type 4 for improper', i
         STOP
      END IF
   END DO
END IF


! Now we will read old data file and convert it simultaneously.  Not sure if
! memory is an issue, but doing it simultaneously will take care of that problem

OPEN(UNIT=12,FILE=datafile,STATUS='OLD',ACTION='READ')
OPEN(UNIT=13,FILE=datafilenew)

READ(12,*)
READ(12,*)

WRITE(13,*) 'LAMMPS converted data file'
WRITE(13,*)

READ(12,*) natoms, dummy
ALLOCATE(iatypenew(natoms))
iatypenew = 0
READ(12,*) nbonds, dummy
READ(12,*) nangles, dummy
READ(12,*) ndihedrals, dummy
READ(12,*) nimpropers, dummy
READ(12,*)

WRITE(13,'(I8,2X,A5)') natoms, 'atoms'
WRITE(13,'(I8,2X,A5)') nbonds, 'bonds'
WRITE(13,'(I8,2X,A6)') nangles, 'angles'
WRITE(13,'(I8,2X,A9)') ndihedrals, 'dihedrals'
IF(nimpropertyp .GT. 0) WRITE(13,'(I8,2X,A9)') nimpropers, 'impropers' ! This might have
WRITE(13,*)                                                            ! to change !!

READ(12,*) natomtypold, dummy
READ(12,*) ! bond
READ(12,*) ! angle
READ(12,*) ! dihedral
READ(12,*) ! improper
READ(12,*) ! blank line

WRITE(13,'(I8,2X,A10)') natomtyp, 'atom types'
WRITE(13,'(I8,2X,A10)') nbondtyp, 'bond types'
WRITE(13,'(I8,2X,A11)') nangletyp, 'angle types'
WRITE(13,'(I8,2X,A14)') ndihedraltyp, 'dihedral types'
IF(nimpropertyp .GT. 0) WRITE(13,'(I8,2X,A14)') nimpropertyp, 'improper types'
WRITE(13,*)

READ(12,*) xlo, xhi, dummy, dummy1
READ(12,*) ylo, yhi, dummy, dummy1
READ(12,*) zlo, zhi, dummy, dummy1
READ(12,*)

WRITE(13,'(2F12.6,X,A7)') xlo, xhi, 'xlo xhi'
WRITE(13,'(2F12.6,X,A7)') ylo, yhi, 'ylo yhi'
WRITE(13,'(2F12.6,X,A7)') zlo, zhi, 'zlo zhi'
WRITE(13,*)

READ(12,*)
READ(12,*)
DO i = 1, natomtypold
   READ(12,*)
END DO
READ(12,*)

WRITE(13,*) 'Masses'
WRITE(13,*)
DO i = 1, natomtyp
   WRITE(13,'(I3,F12.6,2X,A1,2X,A4)') i, imass(i), '#', atypenew(i)
END DO
WRITE(13,*)

READ(12,*)
!READ(12,*) dummy

WRITE(13,*) 'Atoms'
WRITE(13,*)

DO i = 1, natoms
   READ(12,*) j, imolecule, iatypeold, tempcharge, x, y, z
   DO j = 1, natomtyp
      IF(abs(tempcharge - icharge(j)) .LT. tol) EXIT
   END DO
   IF(j == natomtyp + 1) THEN
      WRITE(*,*) 'Atom type not found in Atoms section for atom:', i
      STOP
   ELSE
      iatypenew(i) = j
   END IF
   WRITE(13,'(I8,I6,I3,F12.8,3F15.9)') i, imolecule, j, icharge(j), x, y, z
END DO

READ(12,*)
READ(12,*)
READ(12,*)

WRITE(13,*)
WRITE(13,*) 'Bonds'
WRITE(13,*)

DO i = 1, nbonds
   READ(12,*) j, dummyint, atom1, atom2
   atomtype1 =  iatypenew(atom1)
   atomtype2 =  iatypenew(atom2)
   found = .FALSE.
   DO j = 1, nbondtyp
      first = .FALSE.
      IF((atomtype1 == intbtype1(j)) .OR. (atomtype1 == intbtype2(j))) THEN
         IF(atomtype1 == intbtype1(j)) first = .TRUE.
         IF(first .AND. (atomtype2 == intbtype2(j))) THEN
            newbondtyp = j
            found = .TRUE.
            EXIT
         END IF
         IF((.NOT. first) .AND. (atomtype2 == intbtype1(j))) THEN
            newbondtyp = j
            found = .TRUE.
            EXIT
         END IF
      END IF
      IF(j == nbondtyp .AND. (.NOT. found)) THEN
         WRITE(*,*) 'Bondtype not found for bond:', i
         STOP
      END IF
   END DO
   WRITE(13,'(4I8,3A4)') i, newbondtyp, atom1, atom2, '#', &
             atypenew(iatypenew(atom1)), atypenew(iatypenew(atom2))  
END DO

READ(12,*)
READ(12,*)
READ(12,*)

WRITE(13,*)
WRITE(13,*) 'Angles'
WRITE(13,*)

DO i = 1, nangles
   READ(12,*) j, dummyint, atom1, atom2, atom3
   atomtype1 =  iatypenew(atom1)
   atomtype2 =  iatypenew(atom2)
   atomtype3 =  iatypenew(atom3)
   found = .FALSE.
   DO j = 1, nangletyp
      first = .FALSE.
      IF((atomtype1 == intagltype1(j)) .OR. (atomtype1 == intagltype3(j))) THEN
         IF(atomtype1 == intagltype1(j)) first = .TRUE.
         IF(first .AND. (atomtype2 == intagltype2(j)) .AND. (atomtype3 == intagltype3(j))) THEN
            newangletyp = j
            found = .TRUE.
            EXIT
         END IF
         IF((.NOT. first) .AND. (atomtype2 == intagltype2(j)) .AND. (atomtype3 == intagltype1(j))) THEN
            newangletyp = j
            found = .TRUE.
            EXIT
         END IF
      END IF
      IF(j == nangletyp .AND. (.NOT. found)) THEN
         WRITE(*,*) 'Angletype not found for angle:', i
         STOP
      END IF
   END DO
   WRITE(13,'(5I8,4A4)') i, newangletyp, atom1, atom2, atom3, '#', &
             atypenew(iatypenew(atom1)), atypenew(iatypenew(atom2)), atypenew(iatypenew(atom3))  
END DO

READ(12,*)
READ(12,*)
READ(12,*)

WRITE(13,*)
WRITE(13,*) 'Dihedrals'
WRITE(13,*)

DO i = 1, ndihedrals
   READ(12,*) j, dummyint, atom1, atom2, atom3, atom4
   atomtype1 =  iatypenew(atom1)
   atomtype2 =  iatypenew(atom2)
   atomtype3 =  iatypenew(atom3)
   atomtype4 =  iatypenew(atom4)
   found = .FALSE.
   DO j = 1, ndihedraltyp
      first = .FALSE.
      IF((atomtype1 == intdtype1(j)) .OR. (atomtype1 == intdtype4(j))) THEN
         IF(atomtype1 == intdtype1(j)) first = .TRUE.
         IF(first .AND. (atomtype2 == intdtype2(j)) .AND. &
                        (atomtype3 == intdtype3(j)) .AND. &
                        (atomtype4 == intdtype4(j))) THEN
            newdihedraltyp = j
            found = .TRUE.
            EXIT
         END IF
         IF((.NOT. first) .AND. (atomtype2 == intdtype3(j)) .AND. &
                                (atomtype3 == intdtype2(j)) .AND. & 
                                (atomtype4 == intdtype1(j))) THEN
            newdihedraltyp = j
            found = .TRUE.
            EXIT
         END IF
      END IF
      IF(j == ndihedraltyp .AND. (.NOT. found)) THEN
         WRITE(*,*) 'Dihedral type not found for dihedral:', i
         STOP
      END IF
   END DO
   WRITE(13,'(6I8,5A4)') i, newdihedraltyp, atom1, atom2, atom3, atom4, '#', &
                         atypenew(iatypenew(atom1)), atypenew(iatypenew(atom2)), &
                         atypenew(iatypenew(atom3)), atypenew(iatypenew(atom4))  
END DO

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! This section skips the impropers.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

IF(nimpropers .GT. 0) THEN
   READ(12,*)
   READ(12,*)
   READ(12,*)

   DO i = 1, nimpropers
      READ(12,*)
   END DO
END IF

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! This section reads the impropers
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


!DO i = 1, nimpropers
!   READ(12,*) j, dummyint, atom1, atom2, atom3, atom4
!   atomtype1 =  iatypenew(atom1)
!   atomtype2 =  iatypenew(atom2)
!   atomtype3 =  iatypenew(atom3)
!   atomtype4 =  iatypenew(atom4)
!   first = .FALSE.
!   found = .FALSE.
!   DO j = 1, ndihedraltyp
!      IF((atomtype1 == intdtype1(j)) .OR. (atomtype1 == intdtype4(j))) THEN
!         IF(atomtype1 == intdtype1(j)) first = .TRUE.
!         IF(first .AND. (atomtype2 == intdtype2(j)) .AND. &
!                        (atomtype3 == intdtype3(j)) .AND. &
!                        (atomtype4 == intdtype4(j))) THEN

!            newangletyp = j
!            found = .TRUE.
!            EXIT
!         END IF
!         IF((.NOT. first) .AND. (atomtype2 == intdtype3(j)) .AND. &
!                                (atomtype3 == intdtype2(j)) .AND. & 
!                                (atomtype4 == intdtype1(j))) THEN
!            newdihedraltyp = j
!            found = .TRUE.
!            EXIT
!         END IF
!      END IF
!      IF(j == ndihedraltyp .AND. (.NOT. found)) THEN
!         WRITE(*,*) 'Dihedral type not found for dihedral:', i
!         STOP
!      END IF
!   END DO
!   WRITE(13,'(6I8,5A4)') i, newdihedraltyp, atom1, atom2, atom3, atom4, '#', &
!                         atypenew(iatypenew(atom1)), atypenew(iatypenew(atom2)), &
!                         atypenew(iatypenew(atom3)), atypenew(iatypenew(atom4))  
!END DO

WRITE(13,*)
WRITE(13,*) 'Pair Coeffs'
WRITE(13,*)

DO i = 1, natomtyp
   WRITE(13,'(I3,F11.7,F10.6,2A3)') i, eps(i), sigma(i), '#', atypenew(i)
END DO

WRITE(13,*)
WRITE(13,*) 'Bond Coeffs'
WRITE(13,*)

DO i = 1, nbondtyp
   WRITE(13,'(I3,2X,F10.6,2X,F10.6,3A3)') i, kbond(i), rbond(i), '#', btype1(i), btype2(i)
END DO

WRITE(13,*)
WRITE(13,*) 'Angle Coeffs'
WRITE(13,*)

DO i = 1, nangletyp
   WRITE(13,'(I3,X,F10.6,2X,F10.6,4A3)') i, kangle(i), theta(i), '#', agltype1(i), &
                                  agltype2(i), agltype3(i)
END DO

WRITE(13,*)
WRITE(13,*) 'Dihedral Coeffs'
WRITE(13,*)

DO i = 1, ndihedraltyp
   WRITE(13,'(I3,4F10.6,5A3)') i, V1(i), V2(i), V3(i), V4(i), '#', dtype1(i), &
                                  dtype2(i), dtype3(i), dtype4(i)
END DO

DO i = 1, nimpropertyp

   IF(i == 1) THEN
      WRITE(13,*)
      WRITE(13,*) 'Improper Coeffs'
      WRITE(13,*)
   END IF

   WRITE(13,'(I3,4F10.6,5A3)') i, V1(i), V2(i), V3(i), V4(i), '#', dtype1(i), &
                                  dtype2(i), dtype3(i), dtype4(i)
END DO



CONTAINS

!****************************************************************************
FUNCTION Int_To_String(int_in)
!****************************************************************************
      IMPLICIT NONE
  !**************************************************************************
  !                                                                         *
  ! This function takes an integer argument
  ! and returns the character equivalent
  !                                                                         *
  !**************************************************************************
  CHARACTER(40) :: int_to_string
  LOGICAL :: is_negative
  INTEGER :: int_in, chop_int, ndigits, curr_digit
  
  int_to_string = ""
  ndigits = 0
  
  !Check to see if integer is zero
  IF (int_in == 0) THEN
     int_to_string(1:1) = "0"
     RETURN
  END IF
  
  !Determine if integer is negative
  IF (int_in < 0) THEN
     is_negative = .TRUE.
     chop_int = -int_in
  ELSE
     is_negative = .FALSE.
     chop_int = int_in
  END IF
  
  !Pop of last digit of integer and fill in string from right to
  !left
  DO
     ndigits = ndigits + 1
     curr_digit = MOD(chop_int,10)
     int_to_string(41-ndigits:41-ndigits) = ACHAR(curr_digit+48)
     chop_int = INT(chop_int / 10.0d0)
     IF (chop_int == 0) EXIT
  END DO
  
  IF (is_negative) int_to_string(40-ndigits:40-ndigits) = "-"
  
  !Left justify string
  int_to_string = ADJUSTL(int_to_string)

END FUNCTION Int_To_String



END PROGRAM
